version: "2"

services:
  bff-asistencia:
    build: 
      dockerfile: ./bff-asistencia/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - bff-asistencia
    ports:
      - 3000:3000
  bff-datosadministradores:
    build: 
      dockerfile: ./bff-datosadministradores/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - bff-datosadministradores
    ports:
      - 3001:3001
  bff-datosasistencia:
    build: 
      dockerfile: ./bff-datosasistencia/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - bff-datosasistencia
    ports:
      - 3002:3002
  bff-datosdocente:
    build: 
      dockerfile: ./bff-datosdocente/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - bff-datosdocente
    ports:
      - 3003:3003
  bff-horarios:
    build: 
      dockerfile: ./bff-horarios/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - bff-horarios
    ports:
      - 3004:3004
  ms-erroresasistencia:
    build: 
      dockerfile: ./ms-erroresasistencia/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - ms-erroresasistencia
    ports:
      - 3005:3005
  ms-gestoradmin:
    build: 
      dockerfile: ./ms-gestoradmin/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - ms-gestoradmin
    ports:
      - 3006:3006
  ms-gestorasistencia:
    build: 
      dockerfile: ./ms-gestorasistencia/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - ms-gestorasistencia
    ports:
      - 3007:3007

  ms-gestordocente:
    build: 
      dockerfile: ./ms-gestordocente/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - ms-gestordocente
    ports:
      - 3008:3008

  ms-registroasistencia:
    build:  
      dockerfile: ./ms-registroasistencia/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - ms-registroasistencia
    ports:
      - 3009:3009

  ms-registrohorarios:
    build:  
      dockerfile: ./ms-registrohorarios/Dockerfile
      context: .

    networks:
      universidad:
        aliases: 
          - ms-registrohorarios
    ports:
      - 3010:3010

  ms-validacionrol:
    build: 
      dockerfile: ./ms-validacionrol/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - ms-validacionrol
    ports:
      - 3011:3011
  ms-verificaciongps:
    build: 
      dockerfile: ./ms-verificaciongps/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - ms-verificaciongps
    ports:
      - 3012:3012
  api-main-wm:
    build: 
      dockerfile: ./API-MAIN-WM/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - api-main-wm
    ports:
      - 3013:3013
  api-main-docente:
    build: 
      dockerfile: ./API-MAIN-Docente/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - api-main-Docente
    ports:
      - 3014:3014
  api-main-admin:
    build: 
      dockerfile: ./API-MAIN-ADMIN/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - api-main-admin
    ports:
      - 3015:3015
  api-web-docente:
    build: 
      dockerfile: ./API-WEB-Docente/Dockerfile
      context: .
    networks:
      universidad:
        aliases: 
          - api-web-Docente
    ports:
      - 3016:3016

networks:
  universidad:




