ALTER TABLE Error
    ADD Fecha DATE,
    ADD Docente VARCHAR(255),
    ADD Ramo VARCHAR(255),
    ADD Sala VARCHAR(255),
    ADD Periodo VARCHAR(255);
ADD FOREIGN KEY (Periodo) REFERENCES Periodo(ID) ON DELETE SET NULL ON UPDATE CASCADE,
ADD FOREIGN KEY (Sala) REFERENCES Sala(ID) ON DELETE SET NULL ON UPDATE CASCADE,
ADD FOREIGN KEY (Ramo) REFERENCES Ramo(Nombre) ON DELETE SET NULL ON UPDATE CASCADE,
ADD FOREIGN KEY (Docente) REFERENCES Docente(RUT) ON DELETE SET NULL ON UPDATE CASCADE;


CREATE TRIGGER set_periodo_before_insert
    BEFORE INSERT ON Error
    FOR EACH ROW
BEGIN
    SET NEW.Periodo = (SELECT Periodo.ID FROM Periodo WHERE Estado = 'Activo');
END;

CREATE TRIGGER set_fecha_before_insert
    BEFORE INSERT ON Error
    FOR EACH ROW
BEGIN
    SET NEW.Fecha = CONVERT_TZ(CURRENT_TIMESTAMP,'+00:00','-03:00');
END;